### ISSUE TITLE
Include generated files in project

### ISSUE THREAD

**Issue by RudeySH** [NeVeSpl/NTypewriter#3] opened 2021-03-09 16:32 UTC
For those of us that are stuck using the legacy project system, can we get an option to include the generated files into the project? For reference, the original TypeWriter did this.

**Comment by NeVeSpl** [comment] 2021-03-09 17:30
That should work out of the box, and probably is caused by #2

**Comment by NeVeSpl** [comment] 2021-03-09 20:42
Fixed in v0.0.3

**Closed by NeVeSpl** 2021-03-09 20:42 UTC
Labels: bug
